### ISSUE TITLE
CSS-Modules

### ISSUE THREAD

**Issue by Terreii** [Terreii/andromeda-viewer#159]
**Is your feature request related to a problem? Please describe.**
Having all styles declared in JS can cause a component file to grow in size. It might also discourage people with no to little JS experience to contribute. And the tooling for CSS-Modules (or Sass) is better.

**Describe the solution you'd like**
Move to [CSS-Modules](https://github.com/css-modules/css-modules).

**Describe alternatives you've considered**
Move to [Sass](https://sass-lang.com/).

**Additional context**
With [CSS Variables](https://caniuse.com/#feat=css-variables) and [CSS Grid](https://caniuse.com/#feat=css-grid) became CSS more powerful. In most cases CSS is now enough. CSS-Modules then allows for scoping.

Themes can be done with CSS Variables, with a default theme added in front of it:
```css
.Main {
  background-color: rgb(110,110,110);
  background-color: var(--selected-dialog-background);
}
```
